#' @include classes.R

setGeneric("plot", function(x, y, ...) standardGeneric("plot"))
setGeneric("as_data_frame", function(x, ...) standardGeneric("as_data_frame"))
setGeneric("as_raster", function(x, ...) standardGeneric("as_raster"))
setGeneric("as_vector", function(x, ...) standardGeneric("as_vector"))
setGeneric("copy", function(x, ...) standardGeneric("copy"))
setGeneric("find_lcp", function(x, y, ...) standardGeneric("find_lcp"))
setGeneric("find_lcps", function(x, ...) standardGeneric("find_lcps"))
setGeneric("get_neighbors", function(x, y, ...) standardGeneric("get_neighbors"))
setGeneric("lcp_finder", function(x, y, ...) standardGeneric("lcp_finder"))
setGeneric("n_cells", function(x, ...) standardGeneric("n_cells"))
setGeneric("projection<-", function(x, value) standardGeneric("projection<-"))
setGeneric("quadtree", function(x, ...) standardGeneric("quadtree"))
setGeneric("read_quadtree", function(x, ...) standardGeneric("read_quadtree"))
setGeneric("set_values", function(x, y, z, ...) standardGeneric("set_values"))
setGeneric("summarize_lcps", function(x, ...) standardGeneric("summarize_lcps"))
setGeneric("transform_values", function(x, y, ...) standardGeneric("transform_values"))
setGeneric("write_quadtree", function(x, y, ...) standardGeneric("write_quadtree"))
